# Generated by Django 6.1.1 on 2026-09-10 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='사이트명')),
                ('status', models.CharField(choices=[('active', '운영'), ('pending', '구축 예정'), ('closed', '종료')], db_index=True, default='active', max_length=16, verbose_name='상태')),
                ('build_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='구축년도')),
                ('business_code', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='사업 코드')),
                ('maintenance_code', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='유지보수 코드')),
                ('contract_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='계약 구분')),
                ('sales_manager', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='담당 영업')),
                ('support_staff', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='지원/인력')),
                ('current_file_date', models.DateField(blank=True, null=True, verbose_name='현행화 일자')),
                ('supplied_server_os_db', models.BooleanField(default=False, verbose_name='Server/OS/DB 납품')),
                ('remote_support', models.BooleanField(db_index=True, default=False, verbose_name='원격 지원')),
                ('address', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='위치')),
                ('notes', models.TextField(blank=True, verbose_name='참고 사항')),
                ('special_notes', models.TextField(blank=True, verbose_name='특이사항 및 전달사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '업체/사이트',
                'verbose_name_plural': '업체/사이트',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', '고객 담당자'), ('sales', '영업'), ('support', '기술 지원'), ('other', '기타')], db_index=True, default='customer', max_length=20, verbose_name='역할')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='이름')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='유선번호')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='휴대전화')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='FAX')),
                ('inspection_report_submitted', models.BooleanField(default=False, verbose_name='점검지 제출')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='ContractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=100, verbose_name='제품')),
                ('package_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='패키지')),
                ('version', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='버전')),
                ('installation_location', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='설치 위치')),
                ('configuration', models.CharField(blank=True, max_length=200, verbose_name='구성')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_products', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('database', 'DB'), ('datafile', 'Zenius Datafile'), ('java', 'JAVA'), ('tomcat', 'TOMCAT'), ('manager', 'Manager'), ('log', 'LOG'), ('other', '기타')], db_index=True, max_length=20, verbose_name='항목')),
                ('path', models.CharField(db_index=True, max_length=1000, verbose_name='설치 경로')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='비고')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_locations', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('sms', '단문자'), ('email', '메일'), ('push', 'PushAPP'), ('other', '기타')], db_index=True, max_length=20, verbose_name='연동 유형')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='사용')),
                ('detail', models.TextField(blank=True, verbose_name='상세')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sms', 'SMS'), ('nms', 'NMS'), ('dbms', 'DBMS'), ('apm', 'APM'), ('syslog', 'SYSLOG'), ('trap', 'TRAP'), ('oz', 'OZ 보고서'), ('other', '기타')], db_index=True, max_length=20, verbose_name='분류')),
                ('product_name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='솔루션명')),
                ('license_detail', models.CharField(blank=True, db_index=True, max_length=300, verbose_name='라이선스')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='수량')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='시스템명')),
                ('set_configuration', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Set 구성')),
                ('os_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='OS 종류')),
                ('os_version', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='OS 버전')),
                ('database_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='DB')),
                ('database_version', models.CharField(blank=True, max_length=100, verbose_name='DB 버전')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP 주소')),
                ('system_access_info', models.CharField(blank=True, max_length=500, verbose_name='시스템 접속 정보')),
                ('web_access_info', models.CharField(blank=True, max_length=500, verbose_name='Web 접속 정보')),
                ('web_port', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('database_port', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('dashboard_port', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('manager_1', 'Manager #1'), ('manager_2', 'Manager #2'), ('database', 'DB')], db_index=True, max_length=20, verbose_name='대상')),
                ('cpu', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Memory')),
                ('disk', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Disk')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_specs', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'target'), name='unique_hardware_target_per_company')],
            },
        ),
    ]
