# Generated by Django 6.1.1 on 2026-09-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='com_company',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='com_contact',
        ),
        migrations.AlterModelTable(
            name='contractproduct',
            table='com_contract_product',
        ),
        migrations.AlterModelTable(
            name='hardwarespec',
            table='com_hardware_spec',
        ),
        migrations.AlterModelTable(
            name='installationlocation',
            table='com_installation_location',
        ),
        migrations.AlterModelTable(
            name='integration',
            table='com_integration',
        ),
        migrations.AlterModelTable(
            name='solution',
            table='com_solution',
        ),
        migrations.AlterModelTable(
            name='system',
            table='com_system',
        ),
    ]
