# Generated by Django 6.1.1 on 2026-09-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_table_alter_contact_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='company',
            table_comment='업체 및 사이트 기본 정보: 계약, 담당 영업, 지원 인력, 위치, 원격지원 여부',
        ),
        migrations.AlterModelTableComment(
            name='contact',
            table_comment='업체별 고객·영업·기술지원 담당자 및 연락처',
        ),
        migrations.AlterModelTableComment(
            name='contractproduct',
            table_comment='계약 제품 정보: EMS·Dashboard 패키지, 버전, 설치 위치, 구성',
        ),
        migrations.AlterModelTableComment(
            name='hardwarespec',
            table_comment='하드웨어 사양: Manager #1, Manager #2, DB의 CPU, Memory, Disk',
        ),
        migrations.AlterModelTableComment(
            name='installationlocation',
            table_comment='서버 설치 경로 정보: DB, Zenius Datafile, JAVA, TOMCAT, Manager, LOG',
        ),
        migrations.AlterModelTableComment(
            name='integration',
            table_comment='외부 연동 개발 정보: 단문자, 메일, PushAPP 및 기타 연동 설정',
        ),
        migrations.AlterModelTableComment(
            name='solution',
            table_comment='구축 솔루션과 라이선스 정보: SMS, NMS, DBMS, APM, SYSLOG 등',
        ),
        migrations.AlterModelTableComment(
            name='system',
            table_comment='시스템 구성 정보: OS, DB, IP 주소, 접속 정보 및 서비스 포트',
        ),
        migrations.AlterModelTable(
            name='contractproduct',
            table='com_product',
        ),
        migrations.AlterModelTable(
            name='hardwarespec',
            table='com_spec',
        ),
        migrations.AlterModelTable(
            name='installationlocation',
            table='com_install',
        ),
        migrations.AlterModelTable(
            name='integration',
            table='com_dev',
        ),
        migrations.AlterModelTable(
            name='solution',
            table='com_lic',
        ),
    ]
