# Generated by Django 6.1.1 on 2026-09-10 02:16

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_table_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=200, verbose_name='업체명(기록 시점)')),
                ('table_name', models.CharField(db_index=True, max_length=80, verbose_name='대상 테이블')),
                ('record_id', models.PositiveBigIntegerField(db_index=True, verbose_name='대상 레코드 ID')),
                ('action', models.CharField(choices=[('create', '생성'), ('update', '수정'), ('delete', '삭제')], db_index=True, max_length=10, verbose_name='변경 유형')),
                ('before_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='변경 전 데이터')),
                ('after_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='변경 후 데이터')),
                ('changed_fields', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='변경 컬럼')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='변경 일시')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_history', to='companies.company')),
            ],
            options={
                'db_table': 'com_history',
                'db_table_comment': '업체별 변경 이력: 수정 전후 스냅샷, 변경 컬럼, 변경 시각',
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['company', '-changed_at'], name='com_history_company_time_idx')],
            },
        ),
    ]
