# Generated by Django 6.1.1 on 2026-09-12 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companychangehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', '담당자'), ('viewer', '조회자')], default='manager', max_length=20, verbose_name='권한')),
                ('is_primary', models.BooleanField(default=False, verbose_name='주 담당 사이트')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'com_assignment',
                'db_table_comment': '사용자와 담당 업체를 연결하는 권한 매핑 정보',
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='unique_company_user_assignment')],
            },
        ),
    ]
