# Generated by Django 6.1.1 on 2026-09-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_hardwarecapacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='ip_address',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='IP 주소'),
        ),
    ]
